<?xml version="1.0" encoding="utf-8"?><Database Name="basesite_sc71_analytics" EntityNamespace="analyticsdata._DBML" ContextNamespace="analyticsdata._DBML" Class="analyticsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BSO-DPC-00622;Initial Catalog=basesite_sc71_analytics;User ID=SitecoreInstaller" SettingsObjectName="analyticsdata.Properties.Settings" SettingsPropertyName="basesite_sc71_analyticsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PageEventDefinitions" Member="PageEventDefinitions">
    <Type Name="PageEventDefinition">
      <Column Name="PageEventDefinitionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsSystem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAuthorFeedback" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsGoal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsFailure" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Category1Label" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Category1Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Category2Label" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Category2Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Category3Label" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Category3Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="PageEventDefinition_PageEvent" Member="PageEvents" ThisKey="PageEventDefinitionId" OtherKey="PageEventDefinitionId" Type="PageEvent" />
    </Type>
  </Table>
  <Table Name="dbo.PageEvents" Member="PageEvents">
    <Type Name="PageEvent">
      <Column Name="PageEventId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VisitorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PageEventDefinitionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PageId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VisitId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IntegrationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IntegrationLabel" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DataKey" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="DataCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CustomSorting" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateTime" Member="CreateDate" Storage="_DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="rn" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="PageEventDefinition_PageEvent" Member="PageEventDefinition" ThisKey="PageEventDefinitionId" OtherKey="PageEventDefinitionId" Type="PageEventDefinition" IsForeignKey="true" />
      <Association Name="Visitor_PageEvent" Member="Visitor" ThisKey="VisitorId" OtherKey="VisitorId" Type="Visitor" IsForeignKey="true" />
      <Association Name="Visit_PageEvent" Member="Visit" ThisKey="VisitId" OtherKey="VisitId" Type="Visit" IsForeignKey="true" />
      <Association Name="Page_PageEvent" Member="Page" ThisKey="PageId" OtherKey="PageId" Type="Page" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Visitors" Member="Visitors">
    <Type Name="Visitor">
      <Column Name="VisitorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VisitorClassification" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OverrideVisitorClassification" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AuthenticationLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExternalUser" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="IntegrationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IntegrationLabel" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="rn" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Visitor_PageEvent" Member="PageEvents" ThisKey="VisitorId" OtherKey="VisitorId" Type="PageEvent" />
      <Association Name="Visitor_Visit" Member="Visits" ThisKey="VisitorId" OtherKey="VisitorId" Type="Visit" />
      <Association Name="Visitor_Page" Member="Pages" ThisKey="VisitorId" OtherKey="VisitorId" Type="Page" />
    </Type>
  </Table>
  <Table Name="dbo.Visits" Member="Visits">
    <Type Name="Visit">
      <Column Name="VisitId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VisitorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VisitorVisitIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VisitPageCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TrafficType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AspNetSessionId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReferringSiteId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="KeywordsId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BrowserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserAgentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OsId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ScreenId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CampaignId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RDNS" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="MultiSite" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="LocationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Ip" Type="System.Data.Linq.Binary" DbType="VarBinary(16) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BusinessName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MetroCode" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AreaCode" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IspName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TestSetId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TestValues" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Referrer" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="StateChanged" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DeviceName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rn" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Visit_PageEvent" Member="PageEvents" ThisKey="VisitId" OtherKey="VisitId" Type="PageEvent" />
      <Association Name="Visit_Page" Member="Pages" ThisKey="VisitId" OtherKey="VisitId" Type="Page" />
      <Association Name="Visitor_Visit" Member="Visitor" ThisKey="VisitorId" OtherKey="VisitorId" Type="Visitor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Page">
      <Column Name="PageId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VisitId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VisitorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VisitPageIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ItemLanguage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ItemVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeviceId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(800) NOT NULL" CanBeNull="false" />
      <Column Name="UrlText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TestSetId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TestValues" Type="System.Data.Linq.Binary" DbType="Binary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Duration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Data" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DeviceName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="rn" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Page_PageEvent" Member="PageEvents" ThisKey="PageId" OtherKey="PageId" Type="PageEvent" />
      <Association Name="Visitor_Page" Member="Visitor" ThisKey="VisitorId" OtherKey="VisitorId" Type="Visitor" IsForeignKey="true" />
      <Association Name="Visit_Page" Member="Visit" ThisKey="VisitId" OtherKey="VisitId" Type="Visit" IsForeignKey="true" />
    </Type>
  </Table>
</Database>